### ISSUE TITLE
How best to use shared memory parallelism in Julia?

### ISSUE THREAD

**Issue by MikaelSlevinsky** [JuliaMatrices/HierarchicalMatrices.jl#11]
A `ccall` acts as a thread barrier, so even if it's calling BLAS which is multithreaded, the overhead might be high for exceptionally low-rank data structures. Perhaps there's a better way to thread from the top down.

**Comment by MikaelSlevinsky** [comment]
@dlfivefifty, I've tested removing the `ccall`s to BLAS to allow multithreading the butterfly algorithm (actually, just commenting [these lines](https://github.com/JuliaMatrices/HierarchicalMatrices.jl/blob/master/src/algebra.jl#L113-#L115)). I think the benefits significantly outweigh the costs: for 1D transforms like the Chebyshev--Legendre transform, BLAS improves performance by about 10%, but multithreading can improve performance by a much larger factor. Any comments?

**Comment by dlfivefifty** [comment]
Make sure you aren’t using OpenBLAS for the comparison. But the benefits of BLAS Level 1-2 are very marginal if any. BLAS Level 3 is a different story
