### ISSUE TITLE
KernelMatrix goes into infinite loop

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaMatrices/HierarchicalMatrices.jl#17]
```
using LinearAlgebra
using HierarchicalMatrices

h = 0.05
L = 5.0
N = Int(floor(L/h))
xs = range(-L,L,length=N)

K(x,y) = 1/(1+abs(x-y))


KM = KernelMatrix(K,Array(xs),Array(xs),-L,L,-L,L)
```
goes into an infinite loop. `h=0.1` works.

**Comment by MikaelSlevinsky** [comment]
Apologies for the lack of documentation, but if you look at the example (https://github.com/JuliaMatrices/HierarchicalMatrices.jl/blob/master/examples/Kernel.jl), you will find that the points and their extrema must be reversed. This code executes:
```julia
julia> h = 0.01
0.01

julia> L = 5.0
5.0

julia> N = Int(floor(L/h))
500

julia> xs = reverse!(collect(range(-L, stop =L, length=N)));

julia> K(x,y) = 1/(1+abs(x-y))
K (generic function with 1 method)

julia> KM = KernelMatrix(K, xs, xs, L, -L, L, -L) # hooray!

```
Once the number of points gets sufficiently large, then the quad-tree truly appears. 100 points is not quite enough and ends up being essentially a dense array with defined block boundaries.

**Comment by antoine-levitt** [comment]
Huh, I looked at the examples too fast and missed that. Strange convention but why not. Thanks!
