### ISSUE TITLE
Move to JuliaMatrices?

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaMatrices/HierarchicalMatrices.jl#7]
The benefit is that members (e.g. me and @andreasnoack) can help maintain the package, incorporate apps like Femtobots, etc.

**Comment by MikaelSlevinsky** [comment]
sure. do I need member status to transfer? (Femtobot/attobot are enabled, but somehow Femtobot is not actively upgrading)

**Comment by dlfivefifty** [comment]
I invited you to JuliaMatrices

Ah ok, so the benefit is mostly future apps.

**Comment by MikaelSlevinsky** [comment]
Needs a new tag/edit in METADATA so that the package manager can find it

**Comment by MikaelSlevinsky** [comment]
An owner of JuliaMatrices needs to start/activate an AppVeyor account so that the AppVeyor tests get correctly triggered.

**Comment by dlfivefifty** [comment]
just did it
